version: '3.5'

services:
  professos:
    build: .
    ports:
      - "8080:8080"
    networks:
      professos_default:
        aliases:
          - openid.sso-security.de
          # below FQDN's should match what is in
          # src/main/resources/servernames.properties
          - idp.oidc.honest-sso.de
          - idp.oidc.attack-sso.de
          - rp.oidc.honest-sso.de
          - rp.oidc.attack-sso.de

networks:
  professos_default:
    name: professos-default-net

