version: '3'

services:
  professos:
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      default:
        aliases:
          - openid.sso-security.de
          - idp.oidc.honest-sso.de
          - idp.oidc.attack-sso.de
  relying_party:
    build:
      context: ./docker/
      dockerfile: simple-web-app/Dockerfile
    ports:
      - "8180:8080"
    networks:
      default:
        aliases:
          - honestsp.de
          - www.honestsp.de
  identity_provider:
    image: mitreid-server-webapp:latest
    ports:
      - "8280:8080"
  # reminder: when switching from image to build, uncomment the build argument below
  #                args:
  #                        ISSUER: "honestidp.de:8080"
    networks:
      default:
        aliases:
          - honestidp.de
          - www.honestidp.de
