version: "3"
services:
  elearning_sp:
      build:
        context: ../eLearningSSO/
        dockerfile: oidc/sp_webapp/Dockerfile
        #dockerfile: single-sign-on/Dockerfile
      ports: 
        - "80:80"
        - "443:443"
        - "8788:8787"
      command: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]
      volumes:
        - "../eLearningSSO/oidc/sp_webapp/target/:/opt/jboss/wildfly/standalone/deployments/"
      networks:
        default:
          aliases:
            - "honest-idp.com"
            - "honest-sp.com"
            - "attacker.com"

#              extra_hosts:
#                - "honest-idp.com:127.0.0.1"
#                - "honest-sp.com:127.0.0.1"
#                - "attacker.com:127.0.0.1"
